export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const SET_NEWSLETTER = 'SET_NEWSLETTER';
export const FETCH_NEWSLETTER_ID = 'FETCH_NEWSLETTER_ID';


export const CHANGE_SELECTED_REQUEST_TYPE = 'CHANGE_SELECTED_REQUEST_TYPE';
